# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

keycloak:
  enabled: false
#  auth-server-url: http://localhost:18080/auth
#  realm: camunda-platform
#  resource: CustomTasklist
#  public-client: true
#  principal-attribute: preferred_username


#zeebe.client:
#  broker.gatewayAddress: 127.0.0.1:26500
#  security.plaintext: true
#
#identity.clientId: pouet
#identity.clientSecret: CSf4Jqwcmw6HsEocpslOvVPjZ4t8DUoP
#keycloakUrl: http://localhost:18080
tasklistUrl: x
operateUrl: x

# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  cloud:
    region: x
    clusterId: x
    clientId: x
    clientSecret: x


# used to build links when sending mails
baseUrl: http://localhost:8080

# this is to allow react application launched separately to access the WS
websocket:
  allowedOrigin: "*"

# if set to true, process embedded forms will be pulled from local resources BPMN files. If false, forms will be pulled from Operate process definitions.
embeddedForms.fromLocalResources: false

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB
  datasource:
    url: jdbc:h2:file:./h2/db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
